name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi, Thankyou for contributing to DataStore3 your input helps us and you stay secure while using DataStore3'
        pr-message: 'Please Make sure to read the Code of conduct to keep you and everyone safe.'
